In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier,plot_tree
from sklearn.model_selection import train_test_split
from sklearn import tree
from sklearn.preprocessing import LabelEncoder

In [5]:
data = pd.read_csv("fraud_0.1origbase.csv")

In [6]:
data.head()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud
0,283,CASH_IN,210329.84,C1159819632,3778062.79,3988392.64,C1218876138,1519266.60,1308936.76,0
1,132,CASH_OUT,215489.19,C1372369468,21518.00,0.00,C467105520,6345756.55,6794954.89,0
2,355,DEBIT,4431.05,C1059822709,20674.00,16242.95,C76588246,80876.56,85307.61,0
3,135,CASH_OUT,214026.20,C1464960643,46909.73,0.00,C1059379810,13467450.36,13681476.56,0
4,381,CASH_OUT,8858.45,C831134427,0.00,0.00,C579876929,1667180.58,1676039.03,0

In [40]:
data.isFraud.value_counts()

isFraud
0    635441
1       821
Name: count, dtype: int64

In [41]:
 data.columns

Index(['step', 'type', 'amount', 'nameOrig', 'oldbalanceOrg', 'newbalanceOrig',
       'nameDest', 'oldbalanceDest', 'newbalanceDest', 'isFraud'],
      dtype='object')

In [42]:
data.drop({'step','nameOrig','nameDest'},inplace = True,axis=1)

In [43]:
data

,type,amount,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest,isFraud
0,CASH_IN,210329.84,3778062.79,3988392.64,1519266.60,1308936.76,0
1,CASH_OUT,215489.19,21518.00,0.00,6345756.55,6794954.89,0
2,DEBIT,4431.05,20674.00,16242.95,80876.56,85307.61,0
3,CASH_OUT,214026.20,46909.73,0.00,13467450.36,13681476.56,0
4,CASH_OUT,8858.45,0.00,0.00,1667180.58,1676039.03,0
...,...,...,...,...,...,...,...
636257,CASH_OUT,28761.10,0.00,0.00,328534.52,357295.62,0
636258,CASH_OUT,167820.71,62265.00,0.00,106429.48,274250.18,0
636259,PAYMENT,8898.12,30808.00,21909.88,0.00,0.00,0
636260,CASH_OUT,176147.90,83669.00,0.00,0.00,176147.90,0
636261,CASH_OUT,95142.89,0.00,0.00,431380.07,526522.96,0

In [54]:
data_non_fraud=data[data['isFraud'] ==0][:1000]

In [55]:
data_non_fraud

,type,amount,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest,isFraud
0,CASH_IN,210329.84,3778062.79,3988392.64,1519266.60,1308936.76,0
1,CASH_OUT,215489.19,21518.00,0.00,6345756.55,6794954.89,0
2,DEBIT,4431.05,20674.00,16242.95,80876.56,85307.61,0
3,CASH_OUT,214026.20,46909.73,0.00,13467450.36,13681476.56,0
4,CASH_OUT,8858.45,0.00,0.00,1667180.58,1676039.03,0
...,...,...,...,...,...,...,...
996,CASH_IN,51078.82,484152.00,535230.82,808053.09,756974.26,0
997,CASH_OUT,173942.15,265045.00,91102.85,0.00,173942.15,0
998,PAYMENT,3426.73,29615.00,26188.27,0.00,0.00,0
999,CASH_OUT,336806.33,87690.00,0.00,11210.78,348017.10,0
1000,TRANSFER,243902.10,12203.00,0.00,0.00,243902.10,0

In [56]:
data_fraud = data[data['isFraud']==1]

In [57]:
data_fraud

,type,amount,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest,isFraud
720,CASH_OUT,9265.43,9265.43,0.0,0.00,9265.43,1
1124,CASH_OUT,337974.21,337974.21,0.0,0.00,337974.21,1
1313,CASH_OUT,134227.05,134227.05,0.0,2789107.98,2923335.03,1
2381,TRANSFER,175203.45,175203.45,0.0,0.00,0.00,1
3919,CASH_OUT,1650.08,1650.08,0.0,0.00,1650.08,1
...,...,...,...,...,...,...,...
633586,TRANSFER,71921.70,71921.70,0.0,0.00,0.00,1
633927,TRANSFER,7603589.38,7603589.38,0.0,0.00,0.00,1
633950,TRANSFER,537025.01,537025.01,0.0,0.00,0.00,1
634851,TRANSFER,1059682.92,1059682.92,0.0,0.00,0.00,1
636070,TRANSFER,224378.10,224378.10,0.0,0.00,0.00,1

In [61]:
#concat the above two tables
data = pd.concat([data_non_fraud,data_fraud])

In [62]:
data

,type,amount,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest,isFraud
0,CASH_IN,210329.84,3778062.79,3988392.64,1519266.60,1308936.76,0
1,CASH_OUT,215489.19,21518.00,0.00,6345756.55,6794954.89,0
2,DEBIT,4431.05,20674.00,16242.95,80876.56,85307.61,0
3,CASH_OUT,214026.20,46909.73,0.00,13467450.36,13681476.56,0
4,CASH_OUT,8858.45,0.00,0.00,1667180.58,1676039.03,0
...,...,...,...,...,...,...,...
633586,TRANSFER,71921.70,71921.70,0.00,0.00,0.00,1
633927,TRANSFER,7603589.38,7603589.38,0.00,0.00,0.00,1
633950,TRANSFER,537025.01,537025.01,0.00,0.00,0.00,1
634851,TRANSFER,1059682.92,1059682.92,0.00,0.00,0.00,1
636070,TRANSFER,224378.10,224378.10,0.00,0.00,0.00,1

In [63]:
label_enc = LabelEncoder()

In [64]:
data['type']= label_enc.fit_transform(data['type'])

In [65]:
x=data.drop('isFraud',axis=1)
y=data['isFraud']

In [66]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.25,stratify =y ,random_state =2)

In [67]:
from sklearn.neighbors import KNeighborsClassifier

In [68]:
knn_class = KNeighborsClassifier(n_neighbors=7)

In [73]:
help(knn_class)

Help on KNeighborsClassifier in module sklearn.neighbors._classification object:

class KNeighborsClassifier(sklearn.neighbors._base.KNeighborsMixin, sklearn.base.ClassifierMixin, sklearn.neighbors._base.NeighborsBase)
 |  KNeighborsClassifier(n_neighbors=5, *, weights='uniform', algorithm='auto', leaf_size=30, p=2, metric='minkowski', metric_params=None, n_jobs=None)
 |
 |  Classifier implementing the k-nearest neighbors vote.
 |
 |  Read more in the :ref:`User Guide <classification>`.
 |
 |  Parameters
 |  ----------
 |  n_neighbors : int, default=5
 |      Number of neighbors to use by default for :meth:`kneighbors` queries.
 |
 |  weights : {'uniform', 'distance'}, callable or None, default='uniform'
 |      Weight function used in prediction.  Possible values:
 |
 |      - 'uniform' : uniform weights.  All points in each neighborhood
 |        are weighted equally.
 |      - 'distance' : weight points by the inverse of their distance.
 |        in this case, closer neighbors of a query point will have a
 |        greater influence than neighbors which are further away.
 |      - [callable] : a user-defined function which accepts an
 |        array of distances, and returns an array of the same shape
 |        containing the weights.
 |
 |  algorithm : {'auto', 'ball_tree', 'kd_tree', 'brute'}, default='auto'
 |      Algorithm used to compute the nearest neighbors:
 |
 |      - 'ball_tree' will use :class:`BallTree`
 |      - 'kd_tree' will use :class:`KDTree`
 |      - 'brute' will use a brute-force search.
 |      - 'auto' will attempt to decide the most appropriate algorithm
 |        based on the values passed to :meth:`fit` method.
 |
 |      Note: fitting on sparse input will override the setting of
 |      this parameter, using brute force.
 |
 |  leaf_size : int, default=30
 |      Leaf size passed to BallTree or KDTree.  This can affect the
 |      speed of the construction and query, as well as the memory
 |      required to store the tree.  The optimal value depends on the
 |      nature of the problem.
 |
 |  p : int, default=2
 |      Power parameter for the Minkowski metric. When p = 1, this is
 |      equivalent to using manhattan_distance (l1), and euclidean_distance
 |      (l2) for p = 2. For arbitrary p, minkowski_distance (l_p) is used.
 |
 |  metric : str or callable, default='minkowski'
 |      Metric to use for distance computation. Default is "minkowski", which
 |      results in the standard Euclidean distance when p = 2. See the
 |      documentation of `scipy.spatial.distance
 |      <https://docs.scipy.org/doc/scipy/reference/spatial.distance.html>`_ and
 |      the metrics listed in
 |      :class:`~sklearn.metrics.pairwise.distance_metrics` for valid metric
 |      values.
 |
 |      If metric is "precomputed", X is assumed to be a distance matrix and
 |      must be square during fit. X may be a :term:`sparse graph`, in which
 |      case only "nonzero" elements may be considered neighbors.
 |
 |      If metric is a callable function, it takes two arrays representing 1D
 |      vectors as inputs and must return one value indicating the distance
 |      between those vectors. This works for Scipy's metrics, but is less
 |      efficient than passing the metric name as a string.
 |
 |  metric_params : dict, default=None
 |      Additional keyword arguments for the metric function.
 |
 |  n_jobs : int, default=None
 |      The number of parallel jobs to run for neighbors search.
 |      ``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.
 |      ``-1`` means using all processors. See :term:`Glossary <n_jobs>`
 |      for more details.
 |      Doesn't affect :meth:`fit` method.
 |
 |  Attributes
 |  ----------
 |  classes_ : array of shape (n_classes,)
 |      Class labels known to the classifier
 |
 |  effective_metric_ : str or callble
 |      The distance metric used. It will be same as the `metric` parameter
 |      or a synonym of it, e.g. 'euclidean' if the `metric` parameter set to
 |      'minkowski' and `p` parameter set to 2.
 |
 |  effective_metric_params_ : dict
 |      Additional keyword arguments for the metric function. For most metrics
 |      will be same with `metric_params` parameter, but may also contain the
 |      `p` parameter value if the `effective_metric_` attribute is set to
 |      'minkowski'.
 |
 |  n_features_in_ : int
 |      Number of features seen during :term:`fit`.
 |
 |      .. versionadded:: 0.24
 |
 |  feature_names_in_ : ndarray of shape (`n_features_in_`,)
 |      Names of features seen during :term:`fit`. Defined only when `X`
 |      has feature names that are all strings.
 |
 |      .. versionadded:: 1.0
 |
 |  n_samples_fit_ : int
 |      Number of samples in the fitted data.
 |
 |  outputs_2d_ : bool
 |      False when `y`'s shape is (n_samples, ) or (n_samples, 1) during fit
 |      otherwise True.
 |
 |  See Also
 |  --------
 |  RadiusNeighborsClassifier: Classifier based on neighbors within a fixed radius.
 |  KNeighborsRegressor: Regression based on k-nearest neighbors.
 |  RadiusNeighborsRegressor: Regression based on neighbors within a fixed radius.
 |  NearestNeighbors: Unsupervised learner for implementing neighbor searches.
 |
 |  Notes
 |  -----
 |  See :ref:`Nearest Neighbors <neighbors>` in the online documentation
 |  for a discussion of the choice of ``algorithm`` and ``leaf_size``.
 |
 |  .. warning::
 |
 |     Regarding the Nearest Neighbors algorithms, if it is found that two
 |     neighbors, neighbor `k+1` and `k`, have identical distances
 |     but different labels, the results will depend on the ordering of the
 |     training data.
 |
 |  https://en.wikipedia.org/wiki/K-nearest_neighbor_algorithm
 |
 |  Examples
 |  --------
 |  >>> X = [[0], [1], [2], [3]]
 |  >>> y = [0, 0, 1, 1]
 |  >>> from sklearn.neighbors import KNeighborsClassifier
 |  >>> neigh = KNeighborsClassifier(n_neighbors=3)
 |  >>> neigh.fit(X, y)
 |  KNeighborsClassifier(...)
 |  >>> print(neigh.predict([[1.1]]))
 |  [0]
 |  >>> print(neigh.predict_proba([[0.9]]))
 |  [[0.666... 0.333...]]
 |
 |  Method resolution order:
 |      KNeighborsClassifier
 |      sklearn.neighbors._base.KNeighborsMixin
 |      sklearn.base.ClassifierMixin
 |      sklearn.neighbors._base.NeighborsBase
 |      sklearn.base.MultiOutputMixin
 |      sklearn.base.BaseEstimator
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __init__(self, n_neighbors=5, *, weights='uniform', algorithm='auto', leaf_size=30, p=2, metric='minkowski', metric_params=None, n_jobs=None)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  fit(self, X, y)
 |      Fit the k-nearest neighbors classifier from the training dataset.
 |
 |      Parameters
 |      ----------
 |      X : {array-like, sparse matrix} of shape (n_samples, n_features) or                 (n_samples, n_samples) if metric='precomputed'
 |          Training data.
 |
 |      y : {array-like, sparse matrix} of shape (n_samples,) or                 (n_samples, n_outputs)
 |          Target values.
 |
 |      Returns
 |      -------
 |      self : KNeighborsClassifier
 |          The fitted k-nearest neighbors classifier.
 |
 |  predict(self, X)
 |      Predict the class labels for the provided data.
 |
 |      Parameters
 |      ----------
 |      X : {array-like, sparse matrix} of shape (n_queries, n_features),                 or (n_queries, n_indexed) if metric == 'precomputed'
 |          Test samples.
 |
 |      Returns
 |      -------
 |      y : ndarray of shape (n_queries,) or (n_queries, n_outputs)
 |          Class labels for each data sample.
 |
 |  predict_proba(self, X)
 |      Return probability estimates for the test data X.
 |
 |      Parameters
 |      ----------
 |      X : {array-like, sparse matrix} of shape (n_queries, n_features),                 or (n_queries, n_indexed) if metric == 'precomputed'
 |          Test samples.
 |
 |      Returns
 |      -------
 |      p : ndarray of shape (n_queries, n_classes), or a list of n_outputs                 of such arrays if n_outputs > 1.
 |          The class probabilities of the input samples. Classes are ordered
 |          by lexicographic order.
 |
 |  ----------------------------------------------------------------------
 |  Data and other attributes defined here:
 |
 |  __abstractmethods__ = frozenset()
 |
 |  __annotations__ = {'_parameter_constraints': <class 'dict'>}
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from sklearn.neighbors._base.KNeighborsMixin:
 |
 |  kneighbors(self, X=None, n_neighbors=None, return_distance=True)
 |      Find the K-neighbors of a point.
 |
 |      Returns indices of and distances to the neighbors of each point.
 |
 |      Parameters
 |      ----------
 |      X : {array-like, sparse matrix}, shape (n_queries, n_features),             or (n_queries, n_indexed) if metric == 'precomputed', default=None
 |          The query point or points.
 |          If not provided, neighbors of each indexed point are returned.
 |          In this case, the query point is not considered its own neighbor.
 |
 |      n_neighbors : int, default=None
 |          Number of neighbors required for each sample. The default is the
 |          value passed to the constructor.
 |
 |      return_distance : bool, default=True
 |          Whether or not to return the distances.
 |
 |      Returns
 |      -------
 |      neigh_dist : ndarray of shape (n_queries, n_neighbors)
 |          Array representing the lengths to points, only present if
 |          return_distance=True.
 |
 |      neigh_ind : ndarray of shape (n_queries, n_neighbors)
 |          Indices of the nearest points in the population matrix.
 |
 |      Examples
 |      --------
 |      In the following example, we construct a NearestNeighbors
 |      class from an array representing our data set and ask who's
 |      the closest point to [1,1,1]
 |
 |      >>> samples = [[0., 0., 0.], [0., .5, 0.], [1., 1., .5]]
 |      >>> from sklearn.neighbors import NearestNeighbors
 |      >>> neigh = NearestNeighbors(n_neighbors=1)
 |      >>> neigh.fit(samples)
 |      NearestNeighbors(n_neighbors=1)
 |      >>> print(neigh.kneighbors([[1., 1., 1.]]))
 |      (array([[0.5]]), array([[2]]))
 |
 |      As you can see, it returns [[0.5]], and [[2]], which means that the
 |      element is at distance 0.5 and is the third element of samples
 |      (indexes start at 0). You can also query for multiple points:
 |
 |      >>> X = [[0., 1., 0.], [1., 0., 1.]]
 |      >>> neigh.kneighbors(X, return_distance=False)
 |      array([[1],
 |             [2]]...)
 |
 |  kneighbors_graph(self, X=None, n_neighbors=None, mode='connectivity')
 |      Compute the (weighted) graph of k-Neighbors for points in X.
 |
 |      Parameters
 |      ----------
 |      X : {array-like, sparse matrix} of shape (n_queries, n_features),             or (n_queries, n_indexed) if metric == 'precomputed', default=None
 |          The query point or points.
 |          If not provided, neighbors of each indexed point are returned.
 |          In this case, the query point is not considered its own neighbor.
 |          For ``metric='precomputed'`` the shape should be
 |          (n_queries, n_indexed). Otherwise the shape should be
 |          (n_queries, n_features).
 |
 |      n_neighbors : int, default=None
 |          Number of neighbors for each sample. The default is the value
 |          passed to the constructor.
 |
 |      mode : {'connectivity', 'distance'}, default='connectivity'
 |          Type of returned matrix: 'connectivity' will return the
 |          connectivity matrix with ones and zeros, in 'distance' the
 |          edges are distances between points, type of distance
 |          depends on the selected metric parameter in
 |          NearestNeighbors class.
 |
 |      Returns
 |      -------
 |      A : sparse-matrix of shape (n_queries, n_samples_fit)
 |          `n_samples_fit` is the number of samples in the fitted data.
 |          `A[i, j]` gives the weight of the edge connecting `i` to `j`.
 |          The matrix is of CSR format.
 |
 |      See Also
 |      --------
 |      NearestNeighbors.radius_neighbors_graph : Compute the (weighted) graph
 |          of Neighbors for points in X.
 |
 |      Examples
 |      --------
 |      >>> X = [[0], [3], [1]]
 |      >>> from sklearn.neighbors import NearestNeighbors
 |      >>> neigh = NearestNeighbors(n_neighbors=2)
 |      >>> neigh.fit(X)
 |      NearestNeighbors(n_neighbors=2)
 |      >>> A = neigh.kneighbors_graph(X)
 |      >>> A.toarray()
 |      array([[1., 0., 1.],
 |             [0., 1., 1.],
 |             [1., 0., 1.]])
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from sklearn.neighbors._base.KNeighborsMixin:
 |
 |  __dict__
 |      dictionary for instance variables
 |
 |  __weakref__
 |      list of weak references to the object
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from sklearn.base.ClassifierMixin:
 |
 |  score(self, X, y, sample_weight=None)
 |      Return the mean accuracy on the given test data and labels.
 |
 |      In multi-label classification, this is the subset accuracy
 |      which is a harsh metric since you require for each sample that
 |      each label set be correctly predicted.
 |
 |      Parameters
 |      ----------
 |      X : array-like of shape (n_samples, n_features)
 |          Test samples.
 |
 |      y : array-like of shape (n_samples,) or (n_samples, n_outputs)
 |          True labels for `X`.
 |
 |      sample_weight : array-like of shape (n_samples,), default=None
 |          Sample weights.
 |
 |      Returns
 |      -------
 |      score : float
 |          Mean accuracy of ``self.predict(X)`` w.r.t. `y`.
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from sklearn.base.BaseEstimator:
 |
 |  __getstate__(self)
 |      Helper for pickle.
 |
 |  __repr__(self, N_CHAR_MAX=700)
 |      Return repr(self).
 |
 |  __setstate__(self, state)
 |
 |  get_params(self, deep=True)
 |      Get parameters for this estimator.
 |
 |      Parameters
 |      ----------
 |      deep : bool, default=True
 |          If True, will return the parameters for this estimator and
 |          contained subobjects that are estimators.
 |
 |      Returns
 |      -------
 |      params : dict
 |          Parameter names mapped to their values.
 |
 |  set_params(self, **params)
 |      Set the parameters of this estimator.
 |
 |      The method works on simple estimators as well as on nested objects
 |      (such as :class:`~sklearn.pipeline.Pipeline`). The latter have
 |      parameters of the form ``<component>__<parameter>`` so that it's
 |      possible to update each component of a nested object.
 |
 |      Parameters
 |      ----------
 |      **params : dict
 |          Estimator parameters.
 |
 |      Returns
 |      -------
 |      self : estimator instance
 |          Estimator instance.

In [74]:
knn_class.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=7)

In [75]:
y_pred = knn_class.predict(x_test)

In [76]:
y_pred

array([1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1], dtype=int64)

In [77]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [78]:
accuracy = accuracy_score(y_pred, y_test.values)

In [79]:
accuracy

0.8925438596491229

In [80]:
class_report = classification_report(y_pred, y_test.values)

In [81]:
print(class_report)

              precision    recall  f1-score   support

           0       0.90      0.90      0.90       251
           1       0.88      0.88      0.88       205

    accuracy                           0.89       456
   macro avg       0.89      0.89      0.89       456
weighted avg       0.89      0.89      0.89       456

In [82]:
con_mat = confusion_matrix(y_pred, y_test.values)

In [83]:
print(con_mat)

[[226  25]
 [ 24 181]]